/// <reference lib="webworker" />
import { precacheAndRoute } from "workbox-precaching";

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

// Log service worker activation
console.log("[SW] Service Worker loaded - version 3");

// Push notification handler
self.addEventListener("push", (event) => {
  console.log("[SW] Push event received!");
  console.log("[SW] Push event data:", event.data?.text());

  let data = {
    title: "Nova Transação",
    body: "Uma nova transação foi recebida",
    icon: "/logo-ov.png",
    badge: "/logo-ov.png",
  };

  try {
    if (event.data) {
      const payload = event.data.json();
      console.log("[SW] Parsed payload:", JSON.stringify(payload));
      data = {
        title: payload.title || data.title,
        body: payload.body || data.body,
        icon: payload.icon || data.icon,
        badge: data.badge,
      };
    }
  } catch (e) {
    console.error("[SW] Error parsing push data:", e);
  }

  console.log("[SW] Showing notification:", data.title, data.body);

  const options = {
    body: data.body,
    icon: data.icon,
    badge: data.badge,
    vibrate: [200, 100, 200],
    tag: "transaction-notification",
    renotify: true,
    data: {
      url: "/",
      timestamp: Date.now(),
    },
  } as NotificationOptions;

  event.waitUntil(
    self.registration.showNotification(data.title, options)
      .then(() => console.log("[SW] Notification shown successfully"))
      .catch((err) => console.error("[SW] Failed to show notification:", err))
  );
});

// Notification click handler
self.addEventListener("notificationclick", (event) => {
  console.log("[SW] Notification clicked:", event);
  event.notification.close();

  const urlToOpen = (event.notification.data?.url as string) || "/";

  event.waitUntil(
    self.clients
      .matchAll({ type: "window", includeUncontrolled: true })
      .then((clientList) => {
        for (const client of clientList) {
          if (client.url.includes(self.location.origin) && "focus" in client) {
            client.focus();
            return (client as WindowClient).navigate(urlToOpen);
          }
        }
        if (self.clients.openWindow) {
          return self.clients.openWindow(urlToOpen);
        }
      })
  );
});

// Install event
self.addEventListener("install", () => {
  console.log("[SW] Installing...");
  self.skipWaiting();
});

// Activate event
self.addEventListener("activate", (event) => {
  console.log("[SW] Activating...");
  event.waitUntil(self.clients.claim());
});
